spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/book_my_show?currentSchema=public}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        jdbc:
          timezone: UTC
